CoreDemo/Areas/Admin/Controllers/AdminRolController.cs
using CoreDemo.Areas.Admin.Models;
using CoreDemo.Models;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Moderator")]
    public class AdminRolController : Controller
    {
        private readonly RoleManager<AppRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public AdminRolController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var values = _roleManager.Roles.ToList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddRole(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppRole role = new AppRole
                {
                    Name = model.name
                };

                var result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult UpdateRole(int id)
        {
            var values = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
            RoleUpdateViewModel model = new RoleUpdateViewModel
            {
                Id = values.Id,
                name = values.Name
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateRole(RoleUpdateViewModel model)
        {
            var values = _roleManager.Roles.Where(x=>x.Id == model.Id).FirstOrDefault();
            values.Name = model.name;
            var result = await _roleManager.UpdateAsync(values);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public async Task<IActionResult> DeleteRole(int id)
        {
            var values = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
            var result = await _roleManager.DeleteAsync(values);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult UserRoleList()
        {
            var values = _userManager.Users.ToList();
            return View(values);
        }
        [HttpGet]
        public async Task<IActionResult> AssignRole(int id)
        {
            var user = _userManager.Users.FirstOrDefault(x => x.Id == id);
            var roles = _roleManager.Roles.ToList();

            TempData["UserId"] = user.Id;

            var userRoles = await _userManager.GetRolesAsync(user);

            List<RoleAssignViewModel> model = new List<RoleAssignViewModel>();
            foreach (var item in roles)
            {
                RoleAssignViewModel m = new RoleAssignViewModel();
                m.RoleID = item.Id;
                m.Name = item.Name;
                m.Exists = userRoles.Contains(item.Name);
                model.Add(m);
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AssignRole(List<RoleAssignViewModel> model)
        {
            var userid = (int)TempData["UserId"];
            var user = _userManager.Users.FirstOrDefault(x => x.Id == userid);
            foreach (var item in model)
            {
                if (item.Exists)
                {
                    await _userManager.AddToRoleAsync(user, item.Name);
                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(user, item.Name);
                }
            }
            return RedirectToAction("UserRoleList");
        }
    }
}

CoreDemo/Areas/Admin/Views/AdminRol/AddRole.cshtml
@using CoreDemo.Models
@model RoleViewModel
@{
    ViewData["Title"] = "AddRole";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Rol Ekleme Sayfası</h1>
<form method="post">
    <div class="form-group">
        <label>Rol Başlığı</label>
        <input type="text" name="name" class="form-control" />
    </div>
    <button class="btn btn-info">Kaydet</button>
</form>

CoreDemo/Areas/Admin/Views/AdminRol/AssignRole.cshtml
@model List<RoleAssignViewModel>
@{
    ViewData["Title"] = "AssignRole";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form method="post">
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="form-control">
            <input type="hidden" asp-for="@Model[i].RoleID" />
            <input type="hidden" asp-for="@Model[i].Name" />
            <input type="checkbox" asp-for="@Model[i].Exists" class="form-check-input" />
            <label class="form-check-label" for="@Model[i].Exists">@Model[i].Name</label>
        </div>
    }
    <br />
    <button class="btn btn-info">Değişiklikleri Kaydet</button>
</form>
<br />
<a href="/Admin/AdminRol/UserRoleList/" class="btn btn-primary">Kullanıcı Listesine Dön</a>

CoreDemo/Areas/Admin/Views/AdminRol/Index.cshtml
@using EntityLayer.Concrete
@model List<AppRole>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<html>

<body>

    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">

            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Roller  </h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li>
                                    <a href="#" class="dropdown-item">Config option 1</a>
                                </li>
                                <li>
                                    <a href="#" class="dropdown-item">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Başlık</th>
                                    <th>Sil</th>
                                    <th>Düzenle</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th>@item.Id</th>
                                        <td>@item.Name</td>
                                        <td><a href="/Admin/AdminRol/DeleteRole/@item.Id" class="btn btn-outline-danger">Sil</a></td>
                                        <td><a href="/Admin/AdminRol/UpdateRole/@item.Id" class="btn btn-outline-success">Güncelle</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <a href="/Admin/AdminRol/AddRole/" class="btn btn-outline-primary">Yeni Rol Ekle</a>
                        <a href="/Admin/AdminRol/UserRoleList/" class="btn btn-outline-info">Kullanıcı Rol Listesi</a>
                    </div>
                </div>
            </div>
        </div>

    </div>

</body>

</html>

CoreDemo/Areas/Admin/Views/AdminRol/UpdateRole.cshtml
@using CoreDemo.Models
@model RoleUpdateViewModel

@{
    ViewData["Title"] = "UpdateRole";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Rol Düzenleme Sayfası</h1>

    <form method="post">
        <div class="form-group">
            <label>Role ID</label>
            <input type="text" name="Id" value="@Model.Id" class="form-control" />
        </div>
        <div class="form-group">
            <label>Role Başlığı</label>
            <input type="text" name="name" value="@Model.name" class="form-control" />
        </div>
        <button class="btn btn-success">Rolü Güncelle</button>
    </form>

@*<div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Yazar Profil Bilgileri Düzenleme</h4>
                <br />
                <form class="forms-sample" method="post">
                    <div class="form-group">
                        <label for="exampleInputName1">Role ID</label>
                        <input type="text" asp-for="@Model.Id" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Role Başlığı</label>
                        <input type="text" asp-for="@Model.name" class="form-control" />
                    </div>


                    <button class="btn btn-success">Rolü Güncelle</button>
                </form>
            </div>
        </div>
    </div>*@

@*<h1>Blog Düzenleme Sayfası</h1>
<br />
@using (Html.BeginForm("UpdateRole", "AdminRol", FormMethod.Post))
{
    @Html.Label("Blog ID")
    @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
    <br />
    @Html.Label("Blog Başlığı")
    @Html.TextBoxFor(x => x.name, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
}*@

CoreDemo/Areas/Admin/Views/AdminRol/UserRoleList.cshtml
@using EntityLayer.Concrete
@model List<AppUser>
@{
    ViewData["Title"] = "UserRoleList";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Kullanıcı Rol Listesi</h1>

<table class="table table-bordered">
    <tr>
        <th>Kullanıcı</th>
        <th>Rol Ata</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.UserName</td>
            <td><a href="/Admin/AdminRol/AssignRole/@item.Id/" class="btn btn-outline-warning">Rol Ata</a></td>
        </tr>
    }
</table>
<a href="/Admin/AdminRol/Index/" class="btn btn-outline-primary">Rol Listesine Dön</a>